steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/docker-repos/apub_bot:latest', 'apub_bot_func/.']
images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/docker-repos/apub_bot:latest'