steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/docker-repos/apub_bot:${_IMAGE_TAG}', 'apub_bot_func/.']
images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/docker-repos/apub_bot:${_IMAGE_TAG}'